name: reusable build workflow

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
    secrets:
      GHCR_USER:
        required: true
      GHCR_TOKEN:
        required: true

env:
  BASE_NAME: ${{ inputs.app_name }}

jobs:
  package:
    name: Build image container, store in ghcr.io
    runs-on: ubuntu-18.04 # ATTN - if change, needs also updated `.actrc`

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Package container image (backend)
        uses: docker/build-push-action@v1
        with:
          dockerfile: Dockerfile
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
          repository: wuerthcs/${{ inputs.app_name }}
          add_git_labels: true
          tag_with_ref: true
          tag_with_sha: true

