name: reusablbe package to Github Container Registry

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
    secrets:
      GHCR_USER:
        required: true
      GHCR_TOKEN:
        required: true

jobs:
  package:
    name: Build image container, store in ghcr.io
    runs-on: ubuntu-22.04 # ATTN - if change, needs also updated `.actrc` in main repo!

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/wuerthcs/${{ inputs.app_name }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Package container image and push to the registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
