name: reusablbe package to Github Container Registry

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      dockerfile:
        required: false
        type: string
        default: 'Dockerfile'
    secrets:
      GHCR_USER:
        required: true
      GHCR_TOKEN:
        required: true

jobs:
  package:
    name: Build image container, store in ghcr.io
    runs-on: ubuntu-22.04 # ATTN - if change, needs also updated `.actrc` in main repo!

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Package container image
        uses: docker/build-push-action@v1
        with:
          dockerfile: ${{ inputs.dockerfile }}
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
          repository: wuerthcs/${{ inputs.app_name }}
          add_git_labels: true
          tag_with_ref: true
          tag_with_sha: true
