name: reusable verify w/ Megalint https://megalinter.github.io

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string

jobs:
  verify:
    name: "Verify (lint) with multiple linters"
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: lint all
        # TODO find a better way to support flavors. Cannot use `inputs` in `uses`
        uses: nvuillam/mega-linter@v4
        env:
          # main config via .mega-linter.yml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # TODO this is a hack to enable local runs with act. It's unclear why act doesn't set the path correctly
          # ATTN act is not working w/ reusable workflows anyway
          PATH: '~/.raku/bin:/opt/rakudo-pkg/bin:/opt/rakudo-pkg/share/perl6/site/bin:/root/.composer/vendor/bin:/usr/lib/jvm/java-1.8-openjdk/bin:/root/.cargo/bin:/usr/lib/jvm/java-1.8-openjdk/bin:/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/'
